### ISSUE TITLE
Custom scaling module

### ISSUE THREAD

**Issue by SMEISEN** [KIT-IAI/pyWATTS#167]
**What is your feature request related to?**
* Module request

**Please describe the module/problem**

A module to enable custom scaling and re-scaling of time series with a given `multiplier `and a given `bias`.

**Describe the solution you'd like**

The inputs are multiple pipeline steps. The module is initialized with the parameter `multiplier (default = 1.0)` and `bias (default = 0.0)`.

transform:
`x = x * multiplier + bias`

re-transform:
`x = x / multiplier - bias`

**Comment by benHeid** [comment]
closed by #170
