### ISSUE TITLE
Add summaries to __init__.py

### ISSUE THREAD

**Issue by SMEISEN** [KIT-IAI/pyWATTS#183]
**What is your feature request related to?**
Add following summaries to `pywatts.summaries.__init__.py`

- MAE
- MAPE
- MASE
- MaxErr
- MinErr

**Please describe the module/problem**

Currently, `from pywatts.summaries import MAE, MASE, MASE` etc. is not possible 

**Describe the solution you'd like**
`from pywatts.summaries import MAE, MASE, MASE` etc. is possible 

**What type of Feature Request**
* Feature enhancement

**Comment by benHeid** [comment]
closed by #184
