### ISSUE TITLE
Rolling Kurtosis

### ISSUE THREAD

**Issue by benHeid** [KIT-IAI/pyWATTS#19]
**What is your feature request related to?**
* Module request

**Please describe the module/problem**

The new module should calculate the rolling kurtosis over the complete data. 

**Describe the solution you'd like**
A module calculating the rolling kurtosis over a specified window. Note that this module should also work if the pipeline works in an online mode.

**What type of Feature Request**
* Module request

**Comment by SMEISEN** [comment]
Should the structure base on the module [rolling_mean](https://github.com/KIT-IAI/pyWATTS/blob/a9a869429bc64be7330ace8f65871ecd4ef655d7/pywatts/modules/rolling_mean.py) or does the online mode also require modifications there?

This question also applies to #21
