### ISSUE TITLE
Communication Manager for Online Learning

### ISSUE THREAD

**Issue by kalebphipps** [KIT-IAI/pyWATTS#26]
**What is your feature request related to?**
* Problem related

**Please describe the module/problem**
In online learning, the execution of certain steps is dependent on other steps. An example includes retraining after detecting a drift. At the moment this information flow from previous steps through to new steps can be implemented through global variables in the pipeline definition file. however, if the pipeline is reloaded, this no longer works. Therefore we require a communication manager, where such variables are stored.

**Describe the solution you'd like**
A communication manager to store variables for online learning. Requirements include:
- When the pipeline is saved, the communication manager with all its variables are also saved.
- The steps must have access to the communication manager.
- Decision needs to be made on whether the modules should have access to the communications manager.
- The communication manager should also be thread-safe to enable multiprocessing. These methods should work with the multiprocessing library and the multithreading library.

**What type of Feature Request**
* Core enhancement

**Comment by benHeid** [comment]
Since we add conditionObjects for retraining, this features is not necessary any more.
