### ISSUE TITLE
Variance Extraction Module

### ISSUE THREAD

**Issue by kalebphipps** [KIT-IAI/pyWATTS#28]
**What is your feature request related to?**
* Module request

**Please describe the module/problem**
This module should be able to calculate the variance of a time series

Example:
- Given a window size of 2.
- Input: [1,1,1,2,2,2]
- Expected Output: [0,0,1,0,0]

**Comment by SMEISEN** [comment]
If I am not mistaken the output should be
[0.0 0.0 0.5 0.0 0.0] for sample variance, and
[0.0 0.0 0.25 0.0 0.0] for population variance

Looks similar to #19 and #21, would we allow this output:
[nan, 0.0 0.0 0.5 0.0 0.0] (len = 6)
instead of 
[0.0 0.0 0.5 0.0 0.0] (len = 5)
