### ISSUE TITLE
Statsmodels Wrapper

### ISSUE THREAD

**Issue by marianturowski** [KIT-IAI/pyWATTS#29]
**What is your feature request related to?**
* Module request

**Please describe the module/problem**

Methods from [Statsmodels](https://www.statsmodels.org/devel/index.html) cannot be directly used in a pipeline

**Describe the solution you'd like**

A wrapper that allows to directly use methods from Statsmodels (analogously to the sklearn wrapper)

**Comment by SMEISEN** [comment]
duplicate of #14?

**Comment by kalebphipps** [comment]
Yep, closed since this is a duplicate of issue #14
