### ISSUE TITLE
Transparency of Outputs

### ISSUE THREAD

**Issue by marianturowski** [KIT-IAI/pyWATTS#31]
**Problem**

Currently, the naming and saving location of exported CSV files and figures is unclear (similar to #16).

**Solution**

Suggestion by @olineumann: Maybe it is a good idea to pass a string to the parameters 'to_csv' or 'plot' which would be the name of the csv or png.
Similarly, one could think of a parameter defining the saving location.

**Comment by benHeid** [comment]
Implemented with #35
