### ISSUE TITLE
'Bracket operator' for steps within pipeline not working

### ISSUE THREAD

**Issue by olineumann** [KIT-IAI/pyWATTS#42]
**Describe the bug**
When using the bracket operator (`__getitem__(self, key)`) for steps instead of pipeline steps the pipeline crashing.

**To Reproduce**
Use a step that will return two DataArrays (e.g. FunctionModule) and access it via step[key] for a following step.

**Expected behavior**
Similar to the pipeline step DataArrays can be accessed via the bracket operator.

**Comment by olineumann** [comment]
@benHeid Just saw that I fixed it within the last two weeks but not committed it yet. PR is following today.

**Comment by benHeid** [comment]
Solved with #45
