### ISSUE TITLE
Dict based input for pipeline data.

### ISSUE THREAD

**Issue by olineumann** [KIT-IAI/pyWATTS#43]
**Describe the bug**
Dict containing DataArrays could not be passed to a pipeline even if they are returned from a pipeline.

**To Reproduce**
Pass a dict containing DataArrays to a pipeline object with `train(..)` or `test(..)`

**Expected behavior**
A user should use the output from a pipeline as an input to a new pipeline.

**Comment by olineumann** [comment]
@benHeid Another issue I quickly fixed within the last week. PR following for revision and checking.

**Comment by benHeid** [comment]
Solved with #45
