### ISSUE TITLE
Integration test enhancement

### ISSUE THREAD

**Issue by olineumann** [KIT-IAI/pyWATTS#47]
**What is your feature request related to?**
As a developer, it would be good to run some example code as integration tests. Therefore, we could use GitHub actions.

**Please describe the module/problem**
Currently, no example scenarios are executed to test if pyWATTS is working properly.

**Describe the solution you'd like**
Run the examples provided in the root directory of pyWATTS as integration tests by using GitHub actions.

**Comment by benHeid** [comment]
solved by #48
