### ISSUE TITLE
Document how to use deep learning in pyWATTS

### ISSUE THREAD

**Issue by benHeid** [KIT-IAI/pyWATTS#8]
**Problem description**

Currently, there is no documentation or example for explaining how Keras/TF or Torch can be used with pyWATTS.

**Solution**
* [x] Example: TorchWrapper
* [x] Example: KerasWrapper
* [x] Example: Creating a new module which contains a keras model
* [x] Example: Creating a new module which contains a torch model
* [x] Documentation section which covers all four examples with additional information

**Comment by SMEISEN** [comment]
As the number of examples increases, we should move them from the root directory to a new folder `examples` with a folder structure corresponding to the modules and wrappers.

**Comment by kalebphipps** [comment]
Add in PNN example and then it is finished
