### ISSUE TITLE
Provide links to documentation for data input and output

### ISSUE THREAD

**Issue by kalebphipps** [KIT-IAI/pyWATTS#9]
Data input and output is managed by the user with standard python packages. Therefore our documentation should link to the following python packages so that the user can familiarise themselves with these methods:

- [x] Xarray.
- [x] Pandas.
- [ ] Numpy.

**Comment by benHeid** [comment]
@kalebphipps I only added links to xarray and pandas, since we only allow xarray Datasets or pandas dataframes as input. Consequently, I close this issue despite a missing link to numpy.
